### ISSUE TITLE
Error: incorrect header check at Zlib._handle.onerror (zlib.js:363:17)

### ISSUE THREAD

**Issue by spacewrench** [Mashape/unirest-nodejs#84]
Similar errors appear to have shown up in other packages, but I don't see a reliable resolution (it's always "reinstall and everything works").  I am trying to GET a .torrent file from an https server, and I always get:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:363:17)
dhm@media:~/code/torrentzscrape$ node --version
v5.5.0

```

The code I'm executing is:
```
    unirest.get( 'https://torrentproject.se/torrent/8921259D85B8A04CD2DCCB726EB409A0BCC38AFB.torrent' )
        .header( 'User-Agent', 'Mozilla/5.0 compatible (rate-limited node.js scraper)' )
        .end( process_torrent );

```

(warning, possibly NSFW...I just picked a random infohash off torrentz.eu.)

unirest.get(...) works for other documents, it's just this one (which is https and possibly gzip compressed).  wget(...) works to download the document, although the certificate used by torrentproject.se is not signed by a known CA.

**Comment by vot** [comment]
Had the same issue and I created a pull request for the error handling on this (https://github.com/Mashape/unirest-nodejs/pull/78).

Gopefully the pull request will be accepted soon, it's been two months now. In the meantime I'm pointing my app's unirest to the forked branch I put in that pull request which fixes it.

You can do that by replacing unirest line in your package.json with
`"unirest": "git://github.com/vot/unirest-nodejs#fix-handleGZIPResponse"`

It should help, it's just an unhandled error.

**Comment by spacewrench** [comment]
Thanks, I'll try it!

**Comment by nijikokun** [comment]
It has been accepted and is now in Master, has not been released yet, can you let me know if this solved your issue @spacewrench ?

**Comment by vibhor-trantor** [comment]
I got a similar issue in another package when our corporate firewall blocked downloading files bigger than a certain file size
