### ISSUE TITLE
Error: Unexpected end of multipart data

### ISSUE THREAD

**Issue by anilpai** [Mashape/unirest-nodejs#88]
I am trying to use unirest put method to upload a file from form data.
```
Error: Unexpected end of multipart data
    at /Users/anilpai/Desktop/2016-05-autodesk-oss-uploader/node_modules/dicer/lib/Dicer.js:62:28
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

**Comment by nijikokun** [comment]
I have been unable to replicate the issue.

**Comment by anilpai** [comment]
```
var readStream = fs.createReadStream(serverFile);
var endpoint = util.format(config.putFileUploadEndPoint, self.bucket, localFile.replace(/ /g, '+'));
var total = fs.statSync(serverFile).size;

readStream.pipe(
  unirest.put(endpoint)
       .headers({
         'Accept': 'application/json',
         'Content-Type': 'application/octet-stream',
         'Authorization':('Bearer ' + self.accessToken),
         'Content-Length': total
       })
       .end(function(response) {
          if (response.statusCode != 200) {
             return callback(response.statusCode)
           } else {
             return callback(null, response.body);
         }
       }
    )

```

Additional Link of similar issue : https://jira.appcelerator.org/browse/API-1185

Also tried adding readStream.unpipe() and still doesn't solve the issue...
